# Generated by Django 2.2.6 on 2020-12-07 16:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=50)),
                ('memo', models.TextField(max_length=300)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='create_date')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Freetalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=50)),
                ('memo', models.TextField(max_length=300)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='create_date')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='From_mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=50)),
                ('memo', models.TextField(max_length=300)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='create_date')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=50)),
                ('memo', models.TextField(max_length=300)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='create_date')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=50)),
                ('memo', models.TextField(max_length=300)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='create_date')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
        ),
        migrations.CreateModel(
            name='To_mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=50)),
                ('memo', models.TextField(max_length=300)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='create_date')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='To_mark_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.To_mark')),
            ],
        ),
        migrations.CreateModel(
            name='Report_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Report')),
            ],
        ),
        migrations.CreateModel(
            name='Question_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Inquiry')),
            ],
        ),
        migrations.CreateModel(
            name='Freetalk_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Freetalk')),
            ],
        ),
        migrations.CreateModel(
            name='Auth_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Auth')),
            ],
        ),
    ]
