# Generated by Django 2.2.6 on 2021-01-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='memo',
            field=models.TextField(max_length=2000),
        ),
    ]
