# Generated by Django 2.2.6 on 2021-01-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210130_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='memo',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='auth_comment',
            name='text',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='freetalk',
            name='memo',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='freetalk_comment',
            name='text',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='from_mark',
            name='memo',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='text',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='inquiry_comment',
            name='text',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='memo',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='question_comment',
            name='text',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='report',
            name='text',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='report_comment',
            name='text',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='to_mark',
            name='memo',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='to_mark_comment',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
